Foundation_English = float(input("กรุณากรอกคะแนนวิชา Foundation English :\n"))
General_Business = float(input("กรุณากรอกคะแนนวิชา General Business :\n"))
Introduction_to_Computer_Systems = float(input("กรุณากรอกคะแนนวิชา Introduction to Computer Systems :\n"))
Computer_Programming  = float(input("กรุณากรอกคะแนนวิชา Computer Programming :\n"))
print("--- Your Score ---")
print("Foundation English : ",Foundation_English)
print("General Business : ",General_Business)
print("Introduction to Computer Systems : ",Introduction_to_Computer_Systems)
print("Computer Programming : ",Computer_Programming)
